services:
  {{ cookiecutter.project_slug }}:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/project/src
    environment:
      REPO_ROOT: /project/src
      DATA_DIR: /project/data
      PYTHONPATH: /project/src
    shm_size: '16gb'
    # At least one of stdin_open or tty is required to make devcontainer work
    stdin_open: true
    tty: true